export default {
    title: "Edit profile details",
    nameText: "First name",
    lastNameText: "Last name",
    emailText: "Email address",
    phoneText: "Cell phone No.",
    submitButtonText: "Submit edited details",
    placeholderEmail: "Enter email address",
    placeholderPhone: "Enter phone number",
    errorFillFirstName: "You did not fill first name",
    errorFillLastName: "You did not fill last name",
    errorFillEmail: "You did not fill email",
    errorFillPhone: "You did not fill phone number",
    errorMinLength: "Min Lengths should be more than 3",
    errorTooMuch: "Too many characters",
    errorPhoneValidationFailed: "Phone number validation failed",
    errorInvalidEmail: "Invalid email address",
    phoneInvalid: "Please enter a valid phone number",
    pageTitle: "Edit profile",
    emailAlreadyExists: "This e-mail address is already in use.",
    emailInputNotice: "If you change your e-mail address, you will be logged out.",
    firstNamePlaceholder: "Enter first name",
    lastNamePlaceholder: "Enter last name",
};
