export default {
    title: "Editar detalles del perfil",
    nameText: "Nombre",
    lastNameText: "Apellido",
    emailText: "Dirección de correo electrónico",
    phoneText: "Cell phone No.",
    submitButtonText: "Enviar detalles editados",
    placeholderEmail: "Ingrese la dirección de correo electrónico",
    placeholderPhone: "Ingresar número de teléfono",
    errorFillFirstName: "No ingresaste el nombre",
    errorFillLastName: "No ingresaste el apellido",
    errorFillEmail: "No llenó el correo electrónico",
    errorFillPhone: "No completó el número de teléfono",
    errorMinLength: "Las longitudes mínimas deben ser superiores a 3",
    errorTooMuch: "Demasiado texto",
    errorPhoneValidationFailed: "Falló la validación del número de teléfono",
    errorInvalidEmail: "Dirección de correo electrónico inválida",
    pageTitle: "Editar perfil",
    emailAlreadyExists: "This e-mail address is already in use.",
    emailInputNotice: "If you change your e-mail address, you will be logged out.",
    firstNamePlaceholder: "Enter first name",
    lastNamePlaceholder: "Enter last name",
};
