export default {
    orderComplete: "Order Complete",
    receipt: "Receipt",
    orderNumber: "Order Number",
    orderDate: "Order Date",
    deliveryDate: "Delivery Date",
    scheduledDeliveryTime: "Scheduled delivery time",
    shippingAddress: "Shipping Address",
    billingAddress: "Billing address",
    phone: "Phone",
    payment: "Payment",
    continueShopping: "Continue Shopping",
    orderStatus: "Order Status",
    paymentStatus: "Payment Status",
    totalTaxText: "Total Tax",
    pageTitle: "Order Complete",
    deliveryMethod: "Delivery Method",
    estiamtedDeliveryTime: "Estimated Delivery Time",
    pickupAddressText: "Pickup Address",
    storeNameText: "Store Name",
    storeIdText: "Store ID",
    trackOrderGuestText: "The following link can be used to track your order status, save it for later use:",
};
