export default {
    orderComplete: "Orden Completada",
    receipt: "Recibo",
    orderNumber: "Número de orden",
    orderDate: "Fecha de orden",
    deliveryDate: "Fecha de entrega",
    scheduledDeliveryTime: "Hora de entrega programada",
    shippingAddress: "Dirección de entrega",
    billingAddress: "Dirección de Envio",
    phone: "Teléfono",
    payment: "Pago",
    continueShopping: "Seguir comprando",
    orderStatus: "Estado del pedido",
    paymentStatus: "Estado de pago",
    totalTaxText: "Total Tax",
    pageTitle: "Order Complete",
    deliveryMethod: "Delivery Method",
    estiamtedDeliveryTime: "Estimated Delivery Time",
    pickupAddressText: "Pickup Address",
    storeNameText: "Store Name",
    storeIdText: "Store ID",
    trackOrderGuestText: "The following link can be used to track your order status, save it for later use:",
};
