export default {
    title: "Cambiar contraseña",
    btn1Text: "Confirmar cambio de contraseña",
    passwordText: "Contraseña",
    confirmPasswordText: "Confirmar contraseña",
    oldPasswordError: "Contraseña actual incorrecta",
    passwordUpdateSuccess: "Contraseña actualizada correctamente",
    currentPasswordLabel: "Current password",
    newPasswordLabel: "New password",
    newPasswordConfirmLabel: "Confirm new password",
    pageTitle: "Change password",
    passwordTooShort: "Password length must be at least 8 characters long",
    passwordRequired: "This field is required",
    currentPasswordPlaceholder: "Enter current password",
    newPasswordPlaceholder: "Enter new password",
    newPasswordConfirmPlaceholder: "Confirm new password",
};
