export default {
    title: "Orders",
    orderNumberText: "Order number",
    dateText: "Date",
    statusText: "Status",
    billingAddressText: "Billing Address",
    shippingAddressText: "Shipping Address",
    shipmentsText: "Shipments",
    subTotalText: "Subtotal",
    deliveryFeeText: "Delivery fee",
    totalText: "Total",
    quantityText: "Quantity",
    pageTitle: "My Orders",
    paymentStatusText: "Payment Status",
    payNowBtnText: "Pay Now",
    reorderModalTitle: "Review products",
    reorderModalYesText: "Add all to cart",
    reorderModalNoText: "Cancel",
    changeStoreModalSwitchText: "Yes",
    changeStoreMessage:
        "This order was placed on {{storeName}} and you have to switch to this store to reorder. Do you want to change the store?",
    changeStoreModalTitle: "Change store",
    productsNotAvailable: "Sorry, the products in this order are not available anymore.",
    productNotAvailableText: "Product not available.",
    orderAgainBtnText: "Order again",
    deliveryMethodText: "Shipping Method",
    pickupAddressText: "Pickup Address",
    storeNameText: "Store Name",
    storeIdText: "Store ID",
};
