export default {
    title: "Pedidos",
    orderNumberText: "Número de pedido",
    dateText: "Fecha",
    statusText: "Estado",
    billingAddressText: "Dirección de Envio",
    shippingAddressText: "Dirección de Envío",
    shipmentsText: "Envíos",
    subTotalText: "Subtotal",
    deliveryFeeText: "Tarifa de envío",
    totalText: "Total",
    quantityText: "Cantidad",
    pageTitle: "Mis Pedidos",
    paymentStatusText: "Payment Status",
    payNowBtnText: "Pagar Ahora",
    reorderModalTitle: "Review products",
    reorderModalYesText: "Add all to cart",
    reorderModalNoText: "Cancel",
    changeStoreModalSwitchText: "Yes",
    changeStoreModalTitle: "Change store",
    productsNotAvailable: "Sorry, the products in this order are not available anymore.",
    productNotAvailableText: "Product not available.",
    orderAgainBtnText: "Order again",
    deliveryMethodText: "Shipping Method",
    pickupAddressText: "Pickup Address",
    storeNameText: "Store Name",
    storeIdText: "Store ID",
};
