export default {
    viewAllStores: "View all stores",
    useCurrentLocation: "Use current location",
    unitedStates: "USA",
    unitedKingdom: "United Kingdom",
    germany: "Germany",
    france: "France",
    spain: "Spain",
    changeLocation: "Change location",
    quantityText: "Quantity",
    searchPlaceholderText: "Search for product or category",
    searchCategoriesTileText: "Matching categories",
    searchProductsTileText: "Matching products",
    changeStoreConfirmTitle: "Confirmation ❕❕",
    changeStoreConfirmText: "Changing store will clear your 🛒. Are you sure?",
    changeStoreNo: "No",
    changeStoreYes: "Yes",
    item: "item",
    items: "items",
    yourOrder: "Your order",
    deliveryFee: "Delivery fee:",
    total: "Order Total:",
    tax: "Total Tax:",
    checkout: "Checkout",
    viewCart: "View cart",
    removeText: "Remove",
    internalServerError: "Something went wrong 😓, please try again later.",
    deniedGeolocation: "You have to allow geolocation for this feature to work.",
    searchNoResultsFound: "No results found.",
    productNotAvailableText: "Product not available",
};
