export default {
    viewAllStores: "Ver todas las tiendas",
    useCurrentLocation: "Usar ubicación actual",
    unitedStates: "USA",
    unitedKingdom: "Reino Unido",
    germany: "Alemania",
    france: "Francia",
    spain: "España",
    changeLocation: "Cambiar locación",
    quantityText: "Cantidad",
    searchPlaceholderText: "Search for product or category",
    searchCategoriesTileText: "Matching categories",
    searchProductsTileText: "Matching products",
    changeStoreConfirmTitle: "Confirmation ❕❕",
    changeStoreConfirmText: "Changing store will clear your 🛒. Are you sure?",
    changeStoreNo: "No",
    changeStoreYes: "Yes",
    item: "item",
    items: "items",
    yourOrder: "Your order",
    deliveryFee: "Delivery fee:",
    total: "Order Total:",
    tax: "Total Tax:",
    checkout: "Checkout",
    viewCart: "View cart",
    removeText: "Remove",
    internalServerError: "Something went wrong 😓, please try again later.",
    deniedGeolocation: "You have to allow geolocation for this feature to work.",
    searchNoResultsFound: "No results found.",
    productNotAvailableText: "Product not available.",
};
