export default {
    title: "Register",
    nameText: "First name",
    lastNameText: "Last name",
    emailText: "Email address",
    phoneText: "Phone number",
    passwordText: "Password",
    confirmPasswordText: "Confirm password",
    btn1Text: "Continue",
    btn2Text: "Login",
    subtitle1: "Already have an account?",
    placeholderEmail: "Enter email address",
    placeholderPhone: "Enter phone number",
    placeholderPassword: "Enter password",
    placeholderConfirmPassword: "Confirm password",
    errorFillFirstName: "You did not fill first name",
    errorFillLastName: "You did not fill last name",
    errorFillEmail: "You did not fill email",
    errorFillPhone: "You did not fill phone number",
    errorFillPassword: "You did not fill password",
    errorFillConfirmPassword: "You did not fill confirm password",
    errorMinLength: "Password length must be at least 8 characters long",
    errorTooMuch: "Too many characters",
    passwordsDoNotMatch: "The passwords do not match",
    errorPhoneValidationFailed: "Phone number validation failed",
    errorCharactersPassword: "Must include upper, lower, special chars and numbers",
    invalidEmail: "Please enter a valid email address",
    invalidPassowrd: "Invalid password",
    emailAlreadyExists: "Email already exists",
    internalServerError: "Something went wrong 😓, please try again later.",
    pageTitle: "Register new account",
    placeholderFirstName: "Enter first name",
    placeholderLastName: "Enter last name",
};
