export default {
    title: "Registrarse",
    nameText: "Nombre propio",
    lastNameText: "Nombre de familia",
    emailText: "Dirección de correo electrónico",
    phoneText: "Número de teléfono",
    passwordText: "Contraseña",
    confirmPasswordText: "Confirmar contraseña",
    btn1Text: "Seguir",
    btn2Text: "Acceso",
    subtitle1: "¿Ya tienes una cuenta?",
    placeholderEmail: "Introduzca la dirección de correo electrónico",
    placeholderPhone: "Introduzca el número de teléfono",
    placeholderPassword: "Introducir la contraseña",
    placeholderConfirmPassword: "Confirmar contraseña",
    errorFillFirstName: "No ingresaste el nombre",
    errorFillLastName: "No ingresaste el apellido",
    errorFillEmail: "No llenó el correo electrónico",
    errorFillPhone: "No completó el número de teléfono",
    errorFillPassword: "No ingresaste la contraseña",
    errorFillConfirmPassword: "No completó confirmar contraseña",
    errorMinLength: "Password length must be at least 8 characters long",
    errorTooMuch: "Demasiado texto",
    passwordsDoNotMatch: "Las contraseñas no coinciden",
    errorPhoneValidationFailed: "Falló la validación del número de teléfono",
    errorCharactersPassword: "Debe incluir mayúsculas, amantes, caracteres especiales y números",
    invalidEmail: "Please enter a valid email address",
    invalidPassowrd: "Invalid password",
    emailAlreadyExists: "Email already exists",
    internalServerError: "Something went wrong 😓, please try again later.",
    pageTitle: "Register new account",
    placeholderFirstName: "eg: John",
    placeholderLastName: "eg: Doe",
};
