export default {
    title: "Edit address details",
    primaryAddress: "Address line 1",
    secondaryAddress: "Address line 2",
    country: "Country",
    city: "City",
    state: "State",
    firstName: "First Name",
    lastName: "Last Name",
    phone: "Phone",
    phonePlaceholder: "e.g 202-555-0176",
    phoneInvalid: "Please enter valid phone number",
    phoneRequired: "Phone is required",
    firstNamePlaceholder: "e.g John",
    lastNamePlaceholder: "e.g Doe",
    zipCode: "ZIP code",
    addressName: "Name this address",
    primaryAddressPlaceholder: "e.g Appartament 245, 124 Mount Drive",
    secondaryAddressPlaceholder: "e.g Manhattan, New York",
    countryPlaceholder: "USA",
    cityPlaceholder: "e.g New York",
    statePlaceholder: "e.g New York",
    zipCodePlaceholder: "e.g 10019",
    addressNamePlaceholder: "e.g Home",
    checkboxText: "Make primary address",
    submitButtonText: "Submit edited address",
    errorFillPrimaryAddress: "You did not fill primary address",
    errorFillFirstName: "First Name is required",
    errorFillLastName: "Last Name is required",
    errorFillCountry: "You did not fill country",
    errorFillCity: "You did not fill city",
    errorFillState: "You did not fill state",
    errorFillZipCode: "You did not fill zip code",
    pageTitle: "Edit address",
    postalCodeInvalid: "Please enter a valid postal code",
    addressFormTitle: "Currently editing {{addressName}}",
};
