export default {
    title: "Editar detalles de la dirección",
    primaryAddress: "Línea de dirección 1",
    secondaryAddress: "Línea de dirección 2",
    country: "País",
    city: "Ciudad",
    state: "Estado",
    firstName: "Primer nombre",
    lastName: "Apellido",
    phone: "Teléfono",
    phonePlaceholder: "por ejemplo, 202-555-0176",
    phoneInvalid: "Ingrese un número de teléfono válido",
    phoneRequired: "Se requiere teléfono",
    firstNamePlaceholder: "e.g John",
    lastNamePlaceholder: "e.g Doe",
    zipCode: "Código postal",
    addressName: "Ponle un nombre a esta dirección",
    primaryAddressPlaceholder: "e.g Appartament 245, 124 Mount Drive",
    secondaryAddressPlaceholder: "e.g Manhattan, Nueva York",
    countryPlaceholder: "EE. UU.",
    cityPlaceholder: "e.g Nueva York",
    statePlaceholder: "e.g Nueva York",
    zipCodePlaceholder: "e.g 10019",
    addressNamePlaceholder: "p. ej., casa",
    checkboxText: "Hacer dirección principal",
    submitButtonText: "Enviar dirección editada",
    errorFillPrimaryAddress: "No llenó la dirección principal",
    errorFillFirstName: "Se requiere el primer nombre",
    errorFillLastName: "Se requiere apellido",
    errorFillCountry: "No completó el país",
    errorFillCity: "No llenaste la ciudad",
    errorFillState: "No llenaste el estado",
    errorFillZipCode: "No llenó el código postal",
    pageTitle: "Edit address",
    postalCodeInvalid: "Please enter a valid postal code",
    addressFormTitle: "Currently editing {{addressName}}",
};
