export default {
    title: "Login",
    emailText: "Email address",
    passwordText: "Password",
    placeholderEmail: "Enter email address",
    placeholderPassword: "Enter password",
    btn1Text: "Continue",
    btn2Text: "Register",
    subtitle1: "New customer?",
    errorFillEmail: "You did not fill email",
    errorFillPassword: "You did not fill password",
    errorMinLength: "Min Lengths should be more than 3",
    errorTooMuch: "Too many characters",
    errorCharactersPassword: "Must include upper, lower, special chars and numbers",
    errorInvalidCredentials: "Invalid username or password.",
    internalServerError: "Something went wrong 😓, please try again later.",
    loadingText: "Please wait...",
    phoneInvalid: "Please enter a valid phone number",
    pageTitle: "Login",
};
