export default {
    title: "Iniciar sesión",
    emailText: "Dirección de correo electrónico",
    passwordText: "Contraseña",
    placeholderEmail: "Ingrese la dirección de correo electrónico",
    placeholderPassword: "Ingresar contraseña",
    btn1Text: "Continuar",
    btn2Text: "Registrarse",
    subtitle1: "¿Nuevo cliente?",
    errorFillEmail: "No llenó el correo electrónico",
    errorFillPassword: "No ingresaste la contraseña",
    errorMinLength: "Las longitudes mínimas deben ser superiores a 3",
    errorTooMuch: "Demasiado texto",
    errorCharactersPassword: "Debe incluir mayúsculas, amantes, caracteres especiales y números",
    errorInvalidCredentials: "Invalid username or password.",
    internalServerError: "Something went wrong 😾, please try again later.",
    loadingText: "Please wait...",
    phoneInvalid: "Please enter a valid phone number",
    pageTitle: "Iniciar sesión",
};
